#local_backend: true

backend:
  name: git-gateway
  branch: main

locale: mk
media_folder: public/media
public_folder: /media

collections:
  - name: "building"
    label: "Објект"
    folder: "content/buildings"
    format: "json"
    create: true
    slug: "{{code}}"
    summary: "{{code}} - {{basicData.buildingName}}"
    editor:
      preview: false
    fields:
      - { label: "Код", name: "code", widget: "string" }
      - { label: "ЕМБ", name: "emb", widget: "string", required: false }
      - { label: "Решение брoj", name: "number", widget: "string", required: false }
      - { label: "Датум на увидот", name: "dateInspection", widget: "datetime", date_format: "DD.MM.YYYY" }
      - { label: "Увидот го извршил", name: "inspectionBy", widget: "string" }
      - { label: "Главна фотографија од објектот", name: "photo", widget: "image" }
      - label: "1. Основни податоци"
        name: "basicData"
        widget: "object"
        collapsed: false
        fields: 
        - { label: "1.1 Име на објект", name: "buildingName", widget: "string", required: false }
        - { label: "1.2 Датум на градење", name: "dateBuilt", widget: "string", required: false }
        - { label: "1.3 Архитект", name: "architect", widget: "string", required: false }
        - { label: "1.4 Соработници", name: "associates", widget: "list", summary: "{{fields.associate}}", field: { label: "Соработник", name: "associate", widget: "string" }, required: false }
        - { label: "1.5 Инвеститор / сопственик", name: "investorOrOwner", widget: "string", required: false }
        - label: "1.6 Адреса на објектот"
          name: "address"
          widget: "object"
          collapsed: false
          fields: 
          - {label: "Адреса", name: "line", widget: "string"}
          - {label: "Град", name: "city", widget: "string"}
          - {label: "Општина", name: "municipality", widget: "string", required: false}
        - { label: "1.7 GPS координати", name: "coordinates", widget: "map", required: false, default: "{\"type\":\"Point\",\"coordinates\":[21.4331, 41.9981]}"}
        - label: "1.8 Типологија според оригиналната намената"
          name: "originalPurpose"
          widget: "object"
          collapsed: true
          fields: 
          - {label: "Тип", name: "type", widget: "select", required: false, options: ["индивидуален станбен", "колективен станбен", "индустриски", "споменик", "јавен", "комерцијален/деловен", "друго"]}
          - {label: "Забелешка", name: "notes", widget: "string", required: false}
        - label: "1.9 Денешна намена"
          name: "todayPurpose"
          widget: "object"
          collapsed: true
          fields: 
          - {label: "Тип", name: "type", widget: "select", required: false, options: ["индивидуален станбен", "колективен станбен", "индустриски", "споменик", "јавен", "комерцијален/деловен", "друго"]}
          - {label: "Забелешка", name: "notes", widget: "string", required: false}
        - { label: "1.10 Заштитен статус", name: "hasProtectedStatus", widget: "boolean", required: false }
      - label: "2. Опис на оригиналната градба"
        name: "originalData"
        widget: "object"
        collapsed: false
        fields: 
        - {label: "2.1 Општ опис", name: "generalDescription", widget: "text"}
        - {label: "2.2 Хронологија на изградба (проект, градежни фази)", name: "timelineDescription", widget: "string", required: false}
        - {label: "2.3 Катност", name: "floors", widget: "string", required: false}
        - {label: "2.4 Програмски опис (опис на план по катови)", name: "programDescription", widget: "text", required: false}
        - {label: "2.5 Структура", name: "structureDescription", widget: "text", required: false}
        - label: "2.6 Материјалност"
          name: "materiality"
          widget: "object"
          collapsed: true
          fields: 
          - label: "Екстериер"
            name: "exterior"
            widget: "object"
            collapsed: false
            fields: 
            - {label: "Кров", name: "roof", widget: "text", required: false}
            - {label: "Фасада", name: "facade", widget: "text", required: false}
            - {label: "Столарија", name: "carpentry", widget: "text", required: false} 
            - {label: "Партер", name: "parterre", widget: "text", required: false}
          - label: "Ентериер"
            name: "interior"
            widget: "object"
            collapsed: false
            fields: 
            - {label: "Заеднички содржини", name: "sharedContent", widget: "text", required: false}
            - {label: "Приватни содржини", name: "privateContent", widget: "text", required: false}
        - {label: "2.7 Контекст", name: "context", widget: "text", required: false}
      - label: "3. Опис на моменталната состојба на градбата / автентичност и интегритет"
        name: "currentData"
        widget: "object"
        collapsed: true
        fields: 
        - label: "3.1 Материјалност"
          name: "materiality"
          widget: "object"
          collapsed: true
          fields: 
          - label: "Екстериер"
            name: "exterior"
            widget: "object"
            collapsed: false
            fields: 
            - {label: "Кров", name: "roof", widget: "text", required: false}
            - {label: "Фасада", name: "facade", widget: "text", required: false}
            - {label: "Столарија", name: "carpentry", widget: "text", required: false} 
            - {label: "Партер", name: "parterre", widget: "text", required: false}
          - label: "Ентериер"
            name: "interior"
            widget: "object"
            collapsed: false
            fields: 
            - {label: "Заеднички содржини", name: "sharedContent", widget: "text", required: false}
            - {label: "Приватни содржини", name: "privateContent", widget: "text", required: false}
        - label: "3.2 Физичка состојба"
          name: "physicalCondition"
          widget: "object"
          collapsed: true
          fields: 
          - label: "Екстериер"
            name: "exterior"
            widget: "object"
            collapsed: false
            fields: 
            - {label: "Состојба", name: "condition", widget: "select", required: false, options: ["добра", "задоволителна", "многу лоша", "катастрофална"]}
            - {label: "Забелешка", name: "notes", widget: "text", required: false}
          - label: "Ентериер"
            name: "interior"
            widget: "object"
            collapsed: false
            fields: 
            - {label: "Состојба", name: "condition", widget: "select", required: false, options: ["добра", "задоволителна", "многу лоша", "катастрофална"]}
            - {label: "Забелешка", name: "notes", widget: "text", required: false}
        - {label: "3.3 Интервенции, промени, модификации (хронолошки)", name: "modifications", widget: "text", required: false}
        - label: "3.4 Физичка состојба"
          name: "authenticity"
          widget: "object"
          collapsed: true
          fields: 
          - label: "Екстериер"
            name: "exterior"
            widget: "object"
            collapsed: false
            fields: 
            - {label: "Состојба", name: "condition", widget: "select", required: false, options: ["добра", "задоволителна", "многу лоша", "катастрофална"]}
            - {label: "Забелешка", name: "notes", widget: "text", required: false}
          - label: "Ентериер"
            name: "interior"
            widget: "object"
            collapsed: false
            fields: 
            - {label: "Состојба", name: "condition", widget: "select", required: false, options: ["добра", "задоволителна", "многу лоша", "катастрофална"]}
            - {label: "Забелешка", name: "notes", widget: "text", required: false}
      - { label: "4. Закани и ризици", name: "risks", widget: "text", required: false }
      - label: "5. Вредности"
        name: "values"
        widget: "object"
        collapsed: false
        fields: 
        - { label: "Вредност", name: "name", widget: "select", multiple: true, options: ["историскa", "авторство", "архитектонска и естетска", "техничка", "општествена / социјална", "емотивна"]}
        - { label: "Забелешка", name: "dateBuilt", widget: "text", required: false }
      - { label: "6. Препораки", name: "suggestions", widget: "text", required: false }
      - { label: "7. Библиографија", name: "bibliography", widget: "text", required: false }
      - label: "8. Фотографии / цртежи (постојна состојба + архива)"
        name: "photos"
        widget: "image"
        choose_url: false
        required: false
        media_library:
          config:
            multiple: true
            